const GOOGLE_MAP_CONTROL_POSITIONS = {
  BOTTOM: 11,
  BOTTOM_CENTER: 11,
  BOTTOM_LEFT: 10,
  BOTTOM_RIGHT: 12,
  CENTER: 13,
  LEFT: 5,
  LEFT_BOTTOM: 6,
  LEFT_CENTER: 4,
  LEFT_TOP: 5,
  RIGHT: 7,
  RIGHT_BOTTOM: 9,
  RIGHT_CENTER: 8,
  RIGHT_TOP: 7,
  TOP: 2,
  TOP_CENTER: 2,
  TOP_LEFT: 1,
  TOP_RIGHT: 3
}

const CENTER_OF_US = [39.8097343, -98.5556199]
const DEFAULT_ZOOM = 4

const DEFAULT_MARKER_MIN_ZOOM = 0
const DEFAULT_MARKER_MAX_ZOOM = 15
const DEFAULT_MARKER_CLUSTER_RADIUS = 60
const DEFAULT_POLYGON_MIN_ZOOM = 16
const DEFAULT_POLYGON_MAX_ZOOM = 22
const DEFAULT_PARLAY_MIN_ZOOM = 17
const DEFAULT_PARLAY_MAX_ZOOM = 22

export {
  GOOGLE_MAP_CONTROL_POSITIONS,
  CENTER_OF_US,
  DEFAULT_ZOOM,
  DEFAULT_MARKER_MIN_ZOOM,
  DEFAULT_MARKER_MAX_ZOOM,
  DEFAULT_MARKER_CLUSTER_RADIUS,
  DEFAULT_POLYGON_MIN_ZOOM,
  DEFAULT_POLYGON_MAX_ZOOM,
  DEFAULT_PARLAY_MIN_ZOOM,
  DEFAULT_PARLAY_MAX_ZOOM
}
