const CookieMap = {
  USER_TOKEN: "User_Token",
  USER_LAST_LOGIN: "User_Last_Login"
};

const SocialAuthenticationProviders = {
  FACEBOOK: "Facebook",
  GOOGLE: "Google"
};

const ReduxActions = {
  SET_WINDOW: "SET_WINDOW",
  USER_SET: "USER_SET",
  USER_SET_LOGOUT: "USER_SET_LOGOUT",
  USER_GET: "GET_USER",
  USER_UPDATE_LOADING: "USER_UPDATE_LOADING",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USERS_GET: "USERS_GET",
  USER_SET_SETTINGS: "USER_SET_SETTINGS",
  USER_SET_LOGOUT: "USER_SET_LOGOUT",
  USER_CLEAR_API: "USER_CLEAR_API",

  SET_USER_LOCATION: "SET_USER_LOCATION",

  RECEIVE_PROJECTS_SEARCH: "RECEIVE_PROJECTS_SEARCH",

  RESET_REDUX: "RESET_REDUX"
};
export { CookieMap, SocialAuthenticationProviders, ReduxActions };
